#!/usr/bin/env bash

if test -z "$DATA_SOURCE_PORT"
then
    DATA_SOURCE_PORT=5432
fi

if test -z "$DATA_SOURCE_DB"
then
    DATA_SOURCE_DB=postgres
fi

if test -z "$DATA_SOURCE_SSLMODE"
then
    DATA_SOURCE_SSLMODE=disable
fi

if test -z "$DATA_SOURCE_URI" && test -n "$DATA_SOURCE_HOST"
then
    export DATA_SOURCE_URI="${DATA_SOURCE_HOST}:${DATA_SOURCE_PORT}/${DATA_SOURCE_DB}?sslmode=${DATA_SOURCE_SSLMODE}"
fi

exec /opt/postgres_exporter/bin/postgres_exporter "$@"
